---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "cache.quay.io/v1alpha1",
          "kind": "Memcached",
          "metadata": {
            "name": "example"
          },
          "spec": {}
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-05-08T05:15:50Z"
    operators.operatorframework.io/builder: operator-sdk-v1.28.1
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
    categories: Cloud Provider
    containerImage: quay.io/rhn_apal/memcached-operator@sha256:ebbfedd514944e1a2a140f785f900d482eecbfff2e3d67bf76f6ee54569a49bc
    repository: https://github.com/opcert
    support: Community
    description: AWS ACM controller is a service controller for managing ACM resources
      in Kubernetes
  name: e2e-memcached-community-operator.v0.0.100
  namespace: placeholder
spec:
  relatedImages:
    - name: kube-rbac-proxy
      image: gcr.io/kubebuilder/kube-rbac-proxy@sha256:d4883d7c622683b3319b5e6b3a7edfbf2594c18060131a8bf64504805f875522
    - name: memcached-operator
      image: quay.io/rhn_apal/memcached-operator@sha256:ebbfedd514944e1a2a140f785f900d482eecbfff2e3d67bf76f6ee54569a49bc
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Memcached
      name: memcacheds.cache.quay.io
      version: v1alpha1
  description: |-
    Memcached E2E Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAOQAAADkCAYAAACIV4iNAAAACXBIWXMAAAsSAAALEgHS3X78AAAQ/UlEQVR4nO3dX4xUVx0H8O9FgoC1y5CNNKnAUlO1qZVtUhsfsN0mbTRtKIsvvpRCY9InLfTJFyNbTYz1hUVN+uADAxiNibGLtYmxD+xqTdOmSZfUvzUWFiTpNsgwpIFKsdecmd9h786dmZ07c++d3znn+0k2mL1bmdnlu7/z/0RxHIOIdFjFnwORHgwkkSIMJJEiDCSRIgwkkSIMJJEiDCSRIgwkkSIMJJEiDCSRIgwkkSIMJJEiDCSRIgwkkSIMJJEiDCSRIgwkkSIMJJEiDCSRIgwkkSIMJJEiDCSRIgwkkSIMJJEiDCSRIqv5w/BHLYom7JupxPFs6N8PF/EqAcdJCA8A2NXmndQBzAMw4ZxlSPVjIB1Vi6INAKYB7M34Dk5IQGcqcXwm9ZSGioHsQS2KxgFMAjDVaAzAVvmvTgG4lPgHPl/S69kgf+f21MNsFszrBlAt67VTdwxkF7UompQqtLXzVy1j/oFXzX9TieNLqaf5vKZxCeNI6uFgGE4FGMg2pAJVO/TLenUUwFSezcICw9jKhnOazdpyMZAtcmwOWrkEU6p1tYQwtjolf2+1qKpPSxjIhALCmHRUKk7m5mAtiqYAHEw9KN8JCeaMgtfiJQYyoRZFMwM2U3txSvqlMytVHJnSmC7oF8Qg6om+Mpu0OWIgRS2KzFzeodSDYp2SinxG5gsho7h2VLfXwaRhmpOqWXXgtarHQDbDOCaBKLt/5pO6VPMqq2b/GMhmIKt9TLBTZyekOcuVQRkFH0jpp51MPaA8LMgIM5uzPWIgyxnICZ1tzha2YMIXQQdS+o6nUw+oKHVZcJDrggmfhL4f8kDqM1SkEemrnzb9dvmFSAmhV8hLHFkdutyXGLos2ApZi6J9DKMKrJgJITdZJ1OfoWGywZySJYxBCrLJKj/wWuoBaVGXZux0aD+RUCskq6NupitxqBZF87LlLBihBpKjq24wi+rfkN0uQQiuycq5R2eZhfj7fD/NIMQKyeaqm0y1nJWN2t4KMZD7Up8hV5i+5fMyZeWloAIpAwTaNvtSdkd8DWVoFZLV0R9HfByBDS2Q7D/6Zca3RQTBBFJ+m7pwJAb1bqtvU1ghVUjOPfrpoE9rYEMKJJur/vJmbCCIQMrcFXd2+IuBdAyro9+2+jLi6n0gZRSOgfSfF1UyhArJ5moYJnx4l6EEkvy33Yc5Sa8DKT8gHvEYDuerpO8VktUxLM4P7PgeSC4GCIvzFdLbDcrciBymShxHLr9xnyskm6sBkrtanOVzILnVKkxO9yO9DKQ0V7kROUyskAqxOoaLgVSIgQzXiMvbsbwLJDcik8tV0scKyepIDKQinO4gZ0davVoYIM3VN1IPKEQVF69P961CsrlKlpPNVq8C+S7wYOqTFConm63eBDKKoskNwG2pBxQqVsgh27cGWOfR+6HB3O/i98+LQEbNiWBuRKZlXFxo7kuFbAzmvA6cSz2hkDnXj/QqkMeB0dQTChkrZNmi5rVkjaVyx4F1l4C66++JcsMKOQTL5h4f55GPtGSrawvNnQ6kDOYsG017uflxIfXFFCqnmq2uV8i2h1jtAUbZdCXhVLPV9UC2XSpXb86BjHwAXEk9pNA4VSFVLS6XxeHmcOMx+UDLN3TcXgtwDbj6GWBdtzK4B7h6mIsFyKGF5qtTnymYnCY+LkGzwRvPev/GHHChDmxOPUg43gwjQ0nm39esC9+FwgMpVW9CPnLbzX9shTBaJpQPAhd3AhtTDykUE64EMvcma+L6t0n5RhQyDZE1XUcZypDNVeLYib5kboGsNSfoJ8tYU/o2sHBPH5WWoQyXKyeaDzTKaiZda1E0XYsi02E+UtYC79f6bGrvBTbuB66mHpD3XLlhua9AShCrcnfG/rIvRL0MXE99skemT8lQBsmJJmumQJr+YS2KpiSIe1NfUJJ3gJsH+ZtMKB+VqZPUQ/KVX4GUvWXzAA6mHpbsdaAy6N9oltg9BKw7z2V2ofCnySpV8aSWA4i35VTZ3gSwAxjl2tcgOLHQvGsgpYla1VAVk+5snGeVD7PS51Fg9DDXvoZAfbO1YyBlPnF2mH3FTrZ1ed39egYYMf3K/wLvD/O9UaHUN1u7/cOuar3S7S5gTeqTOTD9ys8Ca9mE9ZabFdLMLWo+NOoWYNOW1GfzYZuw3wHe524R72z/dhSpvogpFUgZTd2f+kplvgrUinxFPwHWfgFY/2dWS698HNit+f2kAilNVfW+Dvyv6Nd4FsB9rJZeWQS+qPn9LAukTG84cbfircDojtRni2GrJfuW7vt8o8ejV2uFbHskhlbPNn7hleOs9C33Ald4PIi7Fpc2vqt0I5CyW8OpE9vuADaVVSWtF4D1dwMjnLd0V6T4RPNkhXTyotPnhtCMrMu85ThPuHPOH5tdMt2BlEUATt6NYfqSB4dUrWwz1iwo+FuJzWfqn/xDUbtAoLFBuRZFpjo+n3rqkPtlbeow7QSuHAY+2MDDmtXa1gxlPY7jDRpfo22yOnsnu/Vz4MKwU2D6l7cBI2a/JQd+9LkM1OSHMhIp3bDsTSBN0/VHwMXUgyEw+y0ZTH1+s3zuWmU/0gZSZfnOypyXs0fRpmMGU5efJm5HuwN4WONrtIF06kKSbswZrGVPhazEBpODP8Njvu/JMYYvA/fUouiMWQwjg5oq2EEdPceX58AczWFOAxj2IE8nZmH894HFh4FNHb6Ecvao7OaxdjSbsJZpvZgNFdPDPuHcy0DCgVBCVmE8AdSeAlZxZLY4PwMuPNXmMt82Aw5DD6a3gYQjobTMb+xvAuce6vFEdurNOeDifcDGdh34vwKLt7RvpZgvn6rE8XTqScFsH/KUjz/fNcC6l4Crd6We6GOaU18DNm9r7n27ysO3BtctjGjOW19LfbLJtFYOSR+z1NFYG0gnbgbqh0uhhPxqNoNAdwGjZi7qu0CN4cxupTAarwA3pT65nFlmd7IWRTNlHZBlA3km9cQjNpQ7HdvTeLbZoakwnNmY9cUrhRHZjhM1y0rna1FU+G4o24c0f9Gh1FMPmebgccevp9siJyY8DLx3D/ucN5gDyp4EPjQrplIPO2gzsLOSOXNRcCWOCyliNpDmF/AbqaeeegG4uNejS3ceaX6cnwBWdxik8J7ZDjcNjGRdfdFlYKebuoRypsvX9OXG7VdyYU4wQ+/mrJydwKhvy2dGZMQ2hICaUfTngGv9BNF6FTh/e2PlZV8OV+I412ZsMpAzrm7B6pdZzrYLGHFhWqRfI81jM/EVYPFe4NqngZtuzuEqhmExZxudAv5zGNj8Yg6v4QfAwpODHVtjZigm82rCJgO5T66UC445xMqcmxPK+06G9Hbg2qeAD29TfJbSO8DiLHD9ReDWPEKYlEMgIU3YiUocz6eeZLTswtbQmq1JvjZhs7BBNX9+CVi4GVh9r1z9V0ZgzfaoC8Blc//nW8B6Mwr6cuqr8pVTIK0nKnE80KmNrYGsarw6oCz9jNKFxobWsuHN+m0wR2nYX35vYnhbYXIOJAYNZWsgx+Tux6CZeaw9gVfLUPweOFfA1NEzlTieSn22B8uOgZSO6dGwf0TNK+r+DryvaW8lFeOTxdwTc1Bam5ktq5BglUwxfcvHgNGzqSfkg4KPmHg66wL11FUCrJLLfQ4YlWuj69wf5ZdHin83h2T2omepQIqpIfazVdoPjLAZ65fHG2vQC3dETnXsSdtASpUsfS+Ydh8F1h5u7q+8oO2YEMpmpHl0aGrTckGqtR5PuWsbSDRDOeXrPslBmRPuzPEPfwIWGUw3HQDqa8rbZGDyP9PL2T2pQZ2k0Bad98tMk3yDAz/OMOn4B3C1xEBaJypx3LX52rFColkl55vXWFA3O2Tg55fAOVZM/b4HXBhCGI1dK+2p7FohrVoUzcpp/dQDc+Tgt4BNRS/7ouxaTpsbBjNYOt5pMXqvgdwgpwpw5D8Ds7v/h8DHXN8Q7Quzsfu14TRVW81V4rjtWT09BRLsTw7ELJo+AqwaZN8eDcZUkj8AFzfr2Zi+u90G554DicC3aOXlJeDcj4HNbM6WR2EYjYVKHKcOzuo6qNNKVrEfTj2gnplzV00f5m2gfgCobeG3rlBbdIbR2GquMWj9ZKYKaYW+TStvrwPnjjfnNtexSZsfM4DzKx19xk7Mj3sseUp6X4FEM5RmpH976gH1zZwRMwdcOJbT8RShGpGpjcfKW4kziGX7JwcJpBl5nWUoi2HD+VtWzkxMVTwG1B26K2VZX7LvQIKhLNU/gfO/ANb/GqhwRVCaCeKzwOIdbp6y90Aljk2OBgskGMqhMNMorwLvHZPR2pCrp+NBtI5W4rixTWvgQIKhHDp7KtsrwMY5YJ3vFdSe3O7RNX71Shw3Fp7nEkgshbIa2tmuGpkK+hbw3mvAmt8Bm4Z5iFReArg+odFszS2QFqdEdDIhXQSunASu/wX4xGlgnebFCVvkdLuArkhoHIyVeyDRDOV0c5M9aWdGc/8NvPsvYNVp4EMb1rocz1gG0w/cBly9E3j3AWD1JmC9y6er96mxvrWQQILL7LxiDzC278kcZHxZDlDOygTuI8D19cDaUC8G6qDRjywskGiG0qxon+EuEaKVVeI4yrSWNSuZW5ngUSBEKzMFrNBAYunUARPKE6mHRLRM4YFEM5SX5CwRHgdC1EUpgbTkJLsHeOYrUXulBhJL/coxuaudiBJKDySWmrCmX/l06iFRwIYSSEsuIrmbo7BETUMNJJaPwvJoEArdmUIXBmQlCwnMWli1990TFaXwhQFZyYDPOKslBahxLbyqQGJpwOeATI+wb0mhaJxkri6QlqmWlTge52ICCkTjCA+1gbRkMcE2zluS59wIJOQCWZm33G3b2kSeMbMNbgTSkrsQ2Iwl38zZw5KdCiSWBn1sM5Y7SMgHNy7dcS6QljRjJ2U0lv1Lcpn7gbRkNNb0L59g/5IcdCJ5eavzgbTM/QhyJPvT3N5FDqkmX6qqpXN5kTNiD8gHz/MhrVJ3RHpTIZMSAz9jMiLLikka5XM/pGtYMUmhVHVEKIG0GExS5MaNV0lBBdJKBHMft3rREJyQKbuUIAOZJCesTzGYVJLUNeZJXg7qZJGYLtnNBQZUgn2dwghWyLRaFI1Lc5Y3eFHeDste344YyA7Yz6SczcmKsq4YyB5IP9N83K/+xZJG5uSLiW5NVYuBzKAWRWOJqslpE+pFz2EEA9k/Vk3qQaYwgoEcnFTNfexrUovMYQQDmS85V9YEc5JN2qCdWGl6oxMGsiC1KJqUcO7y8g1SJ8/Ixoa+MJAFk+mTSflgOP21IFUxtT41CwayRAynt46a0fd+mqitGMghkXBOJALKPqd7cqmKSQykEjIgNCkh3R7690M5s0B8Sq5TzBUDqZBMpdhwTrB6qmGCaEI4nUfztB0G0gFSPe0HFyKUb0EOoyosiBYD6SCZUhlnQAtntuOZ7XnVsv5CBtIDLRV0nE3cgdhqWE2el1oWBtJDsqcz+cEq2t0pOT18Rq7YHxoGMhBtQhpyJV2Q698aH8OohJ0wkAGTuVAbzrHEnz4tkq/LVW/zEsB5TQFsxUBSW1JR7eIFJP7UWlkX5Fpw+2HCd0Zz+NphIKkvMldqD/q14YX8Od7y/7mhj8UOpl/XOsUw2+Z/Oxe6bhhIIkWCPwaSSBMGkkgRBpJIEQaSSBEGkkgRBpJIEQaSSBEGkkgRBpJIEQaSSBEGkkgRBpJIEQaSSBEGkkgRBpJIEQaSSBEGkkgRBpJIEQaSSBEGkkgRBpJIEQaSSBEGkkgRBpJIEQaSSBEGkkgRBpJIEQaSSBEGkkgLAP8H3fiyx5ljXaUAAAAASUVORK5CYII=%
    mediatype: image/png
  minKubeVersion: 1.20.0
  displayName: memcached
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cache.quay.io
          resources:
          - memcacheds
          - memcacheds/status
          - memcacheds/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: e2e-memcached-community-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: e2e-memcached-community-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: e2e-memcached-community-operator
          control-plane: controller-manager
        name: e2e-memcached-community-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy@sha256:d4883d7c622683b3319b5e6b3a7edfbf2594c18060131a8bf64504805f875522
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:6789
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=e2e-memcached-community-operator
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/rhn_apal/memcached-operator@sha256:ebbfedd514944e1a2a140f785f900d482eecbfff2e3d67bf76f6ee54569a49bc
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 768Mi
                  requests:
                    cpu: 10m
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: e2e-memcached-community-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: e2e-memcached-community-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ai
  - ml
  links:
  - name: Memcached Operator
    url: https://e2e-memcached-community-operator.domain
  maintainers:
  - email: apal@redhat.com
    name: avnish
  maturity: alpha
  provider:
    name: RedHat
    url: www.redhat.com
  version: 0.0.100
