---
# The catalog for intended distribution.
organization: community-operators

# list of repo maintainers for approval 
# in case of missing reviewers in ci.yaml file
maintainers:
  - mporrato
  - ezopezo
  - tomasbakk
  - haripate
  - Allda
  - jedinym
